name: Build Android AAB

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Unzip project
        run: |
          unzip -o account_recovery_consultant.zip -d extracted_app

      - name: Build AAB
        run: |
          PROJECT_DIR=$(find extracted_app -name "pubspec.yaml" -exec dirname {} \;)
          cd "$PROJECT_DIR"
          flutter pub get
          flutter build appbundle --release

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: extracted_app/**/build/app/outputs/bundle/release/*.aab
